version: '3'
services:
  db:
    image: "postgres:13"
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - ./database-blocks:/coinblas/blocks/bitcoin/
      - ./database-data:/var/lib/postgresql/data/
      - ./dbinit:/docker-entrypoint-initdb.d/
      - ./backup:/backup/
  builder:
    build: .
    volumes:
      - ./database-blocks:/coinblas/blocks/bitcoin/
