version: '3'
services:
  db:
    build: db
    shm_size: 1g
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - ./database-blocks:/coinblas/blocks/bitcoin/
      - ./database-data:/var/lib/postgresql/data/
      - ./dbinit:/docker-entrypoint-initdb.d/
      - ./backup:/backup/
  builder:
    build: .
    volumes:
      - .:/home/jovyan/coinblas
    environment:
      COINBLAS_DB: "host=db dbname=coinblas user=postgres password=postgres"
      COINBLAS_PATH: /home/jovyan/coinblas/database-blocks
      GOOGLE_APPLICATION_CREDENTIALS: /home/jovyan/coinblas/pgsodium-e46130a430c2.json
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/coinblas
    environment:
      NB_UID: 1000
      NB_GID: 1000
      GOOGLE_APPLICATION_CREDENTIALS: /home/jovyan/coinblas/pgsodium-e46130a430c2.json
